### ISSUE TITLE
Using with `ReadFrom.Configuration()` advice seems to conflict with the advice above

### ISSUE THREAD

**Issue by hisuwh** [serilog/serilog-sinks-applicationinsights#106]
In your readme you say we should be able to configure Serilog.Sinks.ApplicationInsights using `ReadFrom.Configuration` like so:

```json
    ...
    "WriteTo": [
      {
        "Name": "ApplicationInsights",
        "Args": {
          "instrumentationKey": "YOUR-KEY",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
        }
      }
    ],
    ...
```

However above this you say:
>You can also pass an instrumentation key and this sink will create a new TelemetryConfiguration based on it, however it's actively discouraged compared to using already initialised telemetry configuration, as your telemetry won't be properly correlated.

So can we do something using the telemetryConfiguration through the config?

```json
    ...
    "WriteTo": [
      {
        "Name": "ApplicationInsights",
        "Args": {
          "telemetryConfiguration": "what would go here?",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
        }
      }
    ],
    ...
```

**Comment by DinoSourcesRex** [comment]
If the PR gets approved the corresponding config would be

```
    "WriteTo": [
      {
        "Name": "ApplicationInsights",
        "Args": {
          "restrictedToMinimumLevel": "Information",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.EventTelemetryConverter, Serilog.Sinks.ApplicationInsights"
        }
      }
    ],
```

**Comment by aloneguid** [comment]
Looks good, thank you.

**Comment by hisuwh** [comment]
Niceone @DinoSourcesRex 
The readme ought to be updated as well

**Comment by DinoSourcesRex** [comment]
@hisuwh I can raise a PR for that tomorrow, I am unfortunately totally stacked today. Someone else is free to beat me to it though 😄

**Comment by hisuwh** [comment]
@DinoSourcesRex 
I've done it: https://github.com/serilog/serilog-sinks-applicationinsights/pull/109
