### ISSUE TITLE
Code example on using Serilog and serilog-sinks-applicationinsights on Azure Functions

### ISSUE THREAD

**Issue by PingPongSet** [serilog/serilog-sinks-applicationinsights#113]
I need to use serilog to send message to application insights on Azure Functions.

Below is the code configure serilog sinks application insights. 

var config = TelemetryConfiguration.Active;
            if (config != null)
            {
                Log.Logger = new LoggerConfiguration()
                    .Enrich.FromLogContext()
                    .WriteTo.ApplicationInsights(config, TelemetryConverter.Traces)
                    .CreateLogger();
            }

How to read serilog configuration file?

Is it possible to register logger and inject the logger via constructor?

Please provide code sample.

**Comment by 1zias01** [comment]
https://github.com/serilog/serilog-sinks-applicationinsights

on the very bottom of that page.

```
public static class MyFunctions
{
        static MyFunctions()
        {
            var config = TelemetryConfiguration.Active;
            if (config != null)
            {
                Log.Logger = new LoggerConfiguration()
                    .Enrich.FromLogContext()
                    .WriteTo.ApplicationInsights(config, TelemetryConverter.Traces)
                    .CreateLogger();
            }
        }
}
```

**Comment by PingPongSet** [comment]
Is serilog configuration file needed?

**Comment by 1zias01** [comment]
My guess would be no.  I would assume you only need the core serilog nuget and this sink.  Give it a go and good luck!

**Comment by 1zias01** [comment]
Oh.  He's a sample of how we're doing Function/Method injecting ILogger.

[FunctionName("PurgeData")]
        public static void Run([TimerTrigger("%TimerCronExpression%")]TimerInfo timerInfo, ExecutionContext context, ILogger logger)
        {

            logger.LogInformation($"Data Purger PurgeData TimerTrigger function executed at: {DateTime.Now}");

            var config = new ConfigurationBuilder()
                .SetBasePath(context.FunctionAppDirectory)
                .AddEnvironmentVariables()
                .Build();
}

We use Serilog in Console and Web Apps, but I decided (for now at least) to not user serilog in Function Apps.  As just using ILogger and having the Application Insights Instrumentation Key in the Env Variables (this is the default actually)  will auto-magically log to App Insights in Azure.   Just keeping it simple for now.  

But here's an article that may help you get to where you want to go:
https://stackify.com/logging-azure-functions/
