### ISSUE TITLE
NuGet key has expired

### ISSUE THREAD

**Issue by aloneguid** [serilog/serilog-sinks-applicationinsights#116]
@nblumhardt unfortunately nuget key has expired so we can't publish a new version, could you point me to the right direction to renew it?

See https://ci.appveyor.com/project/serilog/serilog-sinks-applicationinsights/builds/26365959#L243

**Comment by nblumhardt** [comment]
Hi @aloneguid  - it should be sufficient to copy the encrypted key from appveyor.yml in the serilog/serilog repository. Hope this helps! 👍

**Comment by aloneguid** [comment]
Thanks is worked ;)
