### ISSUE TITLE
Build process and project updates

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-applicationinsights#168]
👋 Hi all!

It's been a busy couple of years for everyone, and this repo is overdue for some maintenance, triage, etc.;  @shahiddev and @obi-dann have offered to help out with the backlog, I'll jump in and get the build/release process back in line with the latest in the other `serilog` org projects, hopefully we'll make a bit of a dent in it 🤞 

Just dropping this note here to keep you all in the loop 😄 

 - [x] PRs are landing in `master` - no pre-release packages; will get `dev` back up and running and set to default
 - [x] Versioning - get prefix versioning back up and running
 - [ ] Triage the open PRs
 - [ ] Triage the issue list

CC @aloneguid @joergbattermann (will try not to spam you but please sing out if there's anything we should steer clear of :-))

**Comment by nblumhardt** [comment]
It's been a while since I jumped into this project; looks like the setup is actually quite different in parts from the other Serilog org projects. I'll send a PR rather than hack around directly so everyone has a chance to jump in 😅

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog-sinks-applicationinsights/pull/169

**Comment by shahiddev** [comment]
Apologies for the radio silence @nblumhardt - joining this project at the exact time as a rush at work and a level 4 lockdown were not ideal. 
Planning on putting aside a regular block of time to try and get things moving again.

**Comment by nblumhardt** [comment]
Holding off on any further work here for now - need to put some effort into https://github.com/serilog/serilog/issues/1627 :-) Thanks all!
