### ISSUE TITLE
Ambient Telemetry Logging

### ISSUE THREAD

**Issue by martinfletcher** [serilog/serilog-sinks-applicationinsights#20]
Hey,

I have just configured this sink as per docs, and working as expected for custom logging of events.

One question - Should this sink also log the ambient telemetry as would AI if it was configured directly in an app?

Martin

**Comment by jbattermann** [comment]
Good evening Martin,

nope - not by itself.. the Sink really just logs the Serilog logged messages etc using the AI API (client lib), if you want some of the other AI telemetries you should be able to enable and use these side-by-side just fine but would have to set them up (or pull in the corresponding [other AI nuget packages](https://www.nuget.org/profiles/AppInsightsSdk) etc) yourself.


Cheers,
-Jörg

**Comment by martinfletcher** [comment]
Thanks @jbattermann - So to anyone that comes across this, is this the correct solution:

1. Setup AI to use a custom TelemetryClient - This will be used to log ambient telemetry (perf, etc) as per normal AI does

2. Setup serilog to use the same custom TelemetryClient instance - Shown in the docs (Flushing logs section)

Martin

**Comment by martinfletcher** [comment]
@jbattermann Can you confirm that the above would be the correct approach - Or give guidance on alternatives?

**Comment by jbattermann** [comment]
Hi Martin,

yep that is indeed the correct approach, yes! I'll update the README.md with the next update / package version, too (referencing this issue).

Cheers and thanks!
-Jörg
