### ISSUE TITLE
Severity level is represented as a number

### ISSUE THREAD

**Issue by micgruber** [serilog/serilog-sinks-applicationinsights#203]
**Description**

Currently in azure application insights we see under severityLevel the number of ther severity level and not the text like information, error,...

![image](https://user-images.githubusercontent.com/19686895/176494702-b6720459-3366-4523-9659-54fe91e2f4d5.png)

**Reproduction**

`  "Serilog": {
    "Using": [
      "Serilog.Sinks.ApplicationInsights"
    ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Information"
      }
    },
    "WriteTo": [
      {
        "Name": "ApplicationInsights",
        "Args": {
          "restrictedToMinimumLevel": "Information",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights",
          "instrumentationKey": "key"
        }
      }
    ],
    "Enrich": [ "FromLogContext" ],
    "Properties": {
      "Application": "Sample"
    }
  }`

**Expected behavior**

The severityLevel should be represented as a string.

**Relevant package, tooling and runtime versions**

Serilog.Sinks.ApplicationInsights: 3.1.0

**Comment by micgruber** [comment]
After further investigations I saw that application insights just offers nummeric values for the severity level. So it's not a serilog issue as I initialy thought.

**Comment by nblumhardt** [comment]
Thanks for following up 👍
