### ISSUE TITLE
Binary on nuget package 2.1.0 is not signed

### ISSUE THREAD

**Issue by micdenny** [serilog/serilog-sinks-applicationinsights#23]
After #21 the project does compile and sign the binary, but appveyor skip to upload the new package because the version was not bumped.

~I think we need to bump to a breaking change version `3.0.0` after a binary is signed.~

EDIT: after discussion we decided to bump to a non-breaking change `2.2.0`.

**Comment by jbattermann** [comment]
Thanks @micdenny .. I think maybe @nblumhardt can chime in here: Nicholas, what's your point regarding this / how did the other sinks make the switch from not-signed to signed?

**Comment by nblumhardt** [comment]
Hi @jbattermann - I think a minor version bump (2.2.0) was how we approached it last time. HTH!

**Comment by micdenny** [comment]
@jbattermann should we go for a `2.2.0` then?

**Comment by jbattermann** [comment]
@micdenny yep.. would/could you update the PR?

And thanks @nblumhardt!
