### ISSUE TITLE
LogContext.PushProperties not working with this sink?

### ISSUE THREAD

**Issue by PaybackMan** [serilog/serilog-sinks-applicationinsights#28]
This is a similar question to what was asked from before but I'm trying to get Serilogs LogContext.PushProperties to work when this sink is setup. Basically I'm setting up a collection of Enrichers with values that I want to track (these values come into the service from the controller and I want every log entry down the stack to have them)

          
            using (LogContext.PushProperties(enrichers.ToArray()))
            {
                try
                {
                   // Stuff happens here                  
                }
             }

 None of these properties show up in AI (everything previously worked in Seq). The examples given for this in a previous post seemed to modify the TelemetryClients context on startup. I need this to work per call. Any examples that you guys know of that can get me pointed in the right direction?

Thanks

**Comment by nblumhardt** [comment]
Hi Travis,

Do you have `Enrich.FromLogContext()` set for the new configuration?

Cheers,
Nick

**Comment by jdstuart** [comment]
Has this been resolved? We're having the same issue.

**Comment by aloneguid** [comment]
confirmed that `Enrich.FromLogContext()` resolves the issue, added a test for this
