### ISSUE TITLE
Add support for logging custom dependencies

### ISSUE THREAD

**Issue by cmatskas** [serilog/serilog-sinks-applicationinsights#30]
With the AppInsights API now exposing an option to log external dependencies, would it not make sense to add support for this feature through an extension method in the sink?

Happy to help with this if you need a pair of hands.

**Comment by nblumhardt** [comment]
Would it make sense to pair a general API like [Serilog Timings](https://github.com/nblumhardt/serilog-timings) with some logic in the sink to detect dependency calls, e.g. by matching the event's `MessageTemplate` with one known to represent dependency calls? Just a thought.

**Comment by cmatskas** [comment]
Do you think that would be useful? To me, it feels like we're trying to hijack one sink to accomplish something else. Besides, the dependency mapping API inside AppInsights already has a `timing` feature to provide useful insights. What do you think?

**Comment by nblumhardt** [comment]
Ah, sorry - I think I misunderstood what you were suggesting. Do you have a sketch of the extension method signature we'd use?

**Comment by cmatskas** [comment]
Ah, looking at the custom signature, I may be the one being wrong here. The sample code in the official docs is attached below
```
var startTime = DateTime.UtcNow;
var timer = System.Diagnostics.Stopwatch.StartNew();
try
{
    success = dependency.Call();
}
finally
{
    timer.Stop();
    telemetry.TrackDependency("myDependency", "myCall", startTime, timer.Elapsed, success);
}
```
So, if you go with your suggestion and tie this to the `Serilog.Timings` extension, we may have less work to do and less boilerplate code to write

**Comment by nblumhardt** [comment]
👍 

It might be necessary to create a new extension if we want to collect the precise parameters required by `TrackDependency()`. Doing it as a general-purpose extension, rather than baking it into the sink, does sound like a good way to go, though.

**Comment by aloneguid** [comment]
closing this one as @nblumhardt says it doesn't belong to this project
