### ISSUE TITLE
Example of configuring this sink via LoggerConfiguration().ReadFrom.Configuration(config) and appsettings.json?

### ISSUE THREAD

**Issue by leftside** [serilog/serilog-sinks-applicationinsights#32]
As per the title is there an example of configuring this sink via LoggerConfiguration().ReadFrom.Configuration(config) and appsettings.json when in an ASP.NET Core environment with Visual Studio 2017?

Something like this (for LiterateConsole):
"Serilog": {
    // Log levels include:
    //     Verbose, Debug, Information, Warning, Error, Fatal
    "MinimumLevel": "Verbose",
    "WriteTo": [
      {
        // Color-coded structured logging to console
        "Name": "LiterateConsole",
        "Args": {
          // The optional outputTemplate defines the format of logged messages and provides
          // a way to log additional fields (like ASP.NET Core's RequestId) which may not
          // be included in default message templates.
          "outputTemplate": "{Timestamp:HH:mm:ss} {Level} | {RequestId} - {Message}{NewLine}{Exception}"
        }
      }
    ]

**Comment by gwest** [comment]
@leftside, I've been struggling with this too on .Net Core 2.0.0-preview2, but I have managed to get it working using the following config:

```json
{
  "Serilog": {
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "ApplicationInsightsEvents",
        "Args": { "instrumentationKey": "<MyApplicationInsightsInstrumentationKey>" }
      }
    ]
  }
}
```

**Comment by leftside** [comment]
Thanks @gwest!

**Comment by oliviervaillancourt** [comment]
Hi guys,

I want running into the same issue, thanks for the response.  Trying to apply the same pattern, I'm failing at having a different `restrictedToMinimumLevel` on my `AppInsight` Sink than on my other sinks.

I want to have my `Console` sink on `Debug` and my `AppInsight` sink on `Information`.  Here is what I tried:

```"Serilog": {
     "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
         "Name": "Console",
        "Args": {
                   "outputTemplate": "[{Timestamp:u}][{SourceContext}] - {Level:u5} -- {Message}{NewLine}{Exception}"
        }
      },
      {
        "Name": "ApplicationInsightsTraces",
        "Args": {
         *"restrictedToMinimumLevel": "Information",
          "instrumentationKey": "ee3f051a...."
        }
      }
    ]
  }
```

Any help would be greatly appreciated.  Thanks in advance

**Comment by RSuter** [comment]
With the latest version you need to configure this way (in the sample: traces): 

```
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.ApplicationInsights"
    ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Information"
      }
    },
    "WriteTo": [
      {
        "Name": "ApplicationInsights",
        "Args": {
          "instrumentationKey": "YOUR-KEY",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"

        }
      }
    ],
    "Enrich": [ "FromLogContext" ],
    "Properties": {
      "Application": "Sample"
    }
  }
}
```

@aloneguid Please update the docs with that - we spent a lot of time figuring this out and it might help others... (and it's also not straight forward... :-)

**Comment by aloneguid** [comment]
Awesome work thanks

**Comment by aloneguid** [comment]
added to readme, closing

**Comment by Homulvas** [comment]
You should list this as a breaking change in readme. It's not really that obvious of a change and it's hard to figure out why logging stops to work all of a sudden when package is upgraded.

**Comment by vl-bwalocha** [comment]
Do we really need to have duplicated InstrumentationKey in appsettings.json? 
Even if I vahe confirured key for dotnet in my config:

`
"ApplicationInsights": {
    "InstrumentationKey": "xxx-xxx-xxx"
  },
`

I need to keep it duplicated for SeriLog config section:

`
{
          "Name": "ApplicationInsights",
          "Args": {
            "instrumentationKey": "xxx-xxx-xxx",
            "restrictedToMinimumLevel": "Information",
            "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
          }
        }
`

Is there a plant to improve it?

**Comment by mkgn** [comment]
Still having problems configuring this properly with Azure Web App. I am on .Net 5. Serilog is setup to use the config file as below

        private static void SetupSerilog(IConfigurationRoot config)
        {
            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(config)
                .CreateLogger();
        }

I have Serilog config as below

        {
                "Serilog": {
                        "Using": [
                                "Serilog.Sinks.ApplicationInsights"
                        ],
                        "MinimumLevel": {
                                "Default": "Information",
                                "Override": {
                                        "Microsoft.AspNetCore": "Warning",
                                        "System": "Warning"
                                }
                        },
                        "WriteTo": [
                                {
                                        "Name": "ApplicationInsights",
                                        "Args": {
                                                "instrumentationKey": "mykey",
                                                "restrictedToMinimumLevel": "Information",
                                                "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
                                        }
                                }
                         ],
                        "Enrich": [ "FromLogContext" ],
                         "Properties": {
                                "Application": "myapp"
                        }
                 }
        }

However in my stging slot if I check the active configurations via:
    mysite.scm.azurewebsites.net/Env.cshtml

I see the instrumentation keys in multiple ways (Some are not added by me but azure environment )

APPLICATIONINSIGHTS_CONNECTION_STRING = InstrumentationKey= ""
APPINSIGHTS_INSTRUMENTATIONKEY = ""
APPSETTING_APPINSIGHTS_INSTRUMENTATIONKEY = ""
APPSETTING_APPLICATIONINSIGHTS_CONNECTION_STRING = InstrumentationKey= ""

I am using the key provided in these settings, but login doesn't seem to work, it logs to the standard log file.

What may be going wrong?
