### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by MovGP0** [serilog/serilog-sinks-applicationinsights#38]
when I go to app insights on azure, i get messages that look like `email sent to {email} with status code {StatusCode}.` instead of `email sent to first.last@test.com with status code 200.` 

The code looks like 

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.ApplicationInsightsEvents(configuration["APPINSIGHTS_INSTRUMENTATIONKEY"], LogEventLevel.Info)
    // ...
    .CreateLogger();
```
            
```csharp
Log.Info("email sent to {email} with status code {StatusCode}.", email, result.StatusCode); 
```

Is is possible that the formatting is not working correctly?

**Comment by nblumhardt** [comment]
Hi Johann, I think the `ConvertLogEventsToCustomTraceTelemetry` example in the project README will help with this: https://github.com/serilog/serilog-sinks-applicationinsights/ - HTH!

**Comment by dabutvin** [comment]
I had the same issue today

dropping this in worked for me

```
private static ITelemetry ConvertLogEventsForApplicationInsights(LogEvent logEvent, IFormatProvider formatProvider)
{
     var telemtry = logEvent.ToDefaultTraceTelemetry(
           formatProvider,
           includeLogLevelAsProperty: false,
           includeRenderedMessageAsProperty: false,
           includeMessageTemplateAsProperty: false);

           return telemtry;
}
```

```
.WriteTo.ApplicationInsightsEvents(
            WebConfigurationManager.AppSettings["ApplicationInsightsInstrumentationKey"],
            LogEventLevel.Information,
            CultureInfo.InvariantCulture,
            ConvertLogEventsForApplicationInsights)
```

**Comment by aloneguid** [comment]
I can confirm this is still happening:

![image](https://user-images.githubusercontent.com/3155189/51762465-b5ab6480-20c7-11e9-87fd-a6b06122f813.png)

Considering AI already includes this information, and having it may considerably increase billing, should we make it default for this sink?

**Comment by aloneguid** [comment]
merged the fix
