### ISSUE TITLE
me no can read README.md

### ISSUE THREAD

**Issue by Triwaters** [serilog/serilog-sinks-applicationinsights#43]
I puzzled over this sentence for more than a minute:

For those two LogEvent instances that have Exceptions are always sent as Exceptions to AI though... well, by default.

I'm wondering if it's missing a comma... missing a verb?? Should it read like this?...

For those two LogEvents, instances that have Exceptions are always sent as Exceptions to AI though... well, by default.

Or like this??

For those two LogEvent instances that have Exceptions, [XXXXXXX] are always sent as Exceptions to AI though... well, by default.

I'm thinking the former, but because I am new to the subject matter, I'm unsure. Supposing it's the former... what exactly are "instances" ? Objects? Situations?

**Comment by jbattermann** [comment]
It's more like "me no can _write_ README.md".

What I meant back then was that no matter whether you configure the AI sink to write EventTelemetries or TraceTelemetries, Exceptions are always logged as ExceptionTelemetries.


Non-native speaker + potentially late-night readme fiddling produced that little wonder of a sentence.

**Comment by Triwaters** [comment]
While you fight with English, I'll fight with Serilog... and hopefully both come out fluent? (I think I'll need a bit more help, as you appear to be well ahead of me.) In any case, thanks for clarifying!
