### ISSUE TITLE
Calling Log.CloseAndFlush result in NullReferenceException

### ISSUE THREAD

**Issue by fugaku** [serilog/serilog-sinks-applicationinsights#44]
I'm using ASP.NET Core 2.0

I'm trying to use the ApplicationInsights sink by calling
`.WriteTo.ApplicationInsights(_configuration["ApplicationInsights:InstrumentationKey"], ConvertLogEventsToCustomTraceTelemetry)` as specified on the README

The log then work just fine, telemetry was sent to application insight.

But when the web server is shutting down, I'm calling `Log.CloseAndFlush`

```csharp
            try
            {
                Log.Information("Starting web host");

                var host = BuildWebHost(args);

                host.Run();

                return 0;
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
                return 1;
            }
            finally
            {
                Log.CloseAndFlush();
            }
```

The line calling `Log.CloseAndFlush()` will then throw a NullReferenceException

Stack trace below
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Serilog.Sinks.ApplicationInsights.ApplicationInsightsSinkBase.Dispose(Boolean disposeManagedResources)
   at Serilog.Sinks.ApplicationInsights.ApplicationInsightsSinkBase.Dispose()
   at Serilog.LoggerConfiguration.<CreateLogger>b__28_0()
   at VDMS.Program.Main(String[] args) in C:\Repos\WebApp\Program.cs:line 50
```

I was wondering if I'm doing this the wrong way ?

**Comment by nblumhardt** [comment]
Hi Daniel - your code sample looks correct, so my guess is that this one is a bug.

**Comment by fugaku** [comment]
Thanks for the quick reply.

Any suggestion for the short term workaround ?
Are there any big implications because of this issue ?

**Comment by jbattermann** [comment]
[Looking at the code ](https://github.com/serilog/serilog-sinks-applicationinsights/blob/dd2bd5ca67c8830633b62bb2318a956c9fe36810/src/Serilog.Sinks.ApplicationInsights/Sinks/ApplicationInsights/ApplicationInsightsSinkBase.cs#L228).Dispose() must be called multiple times. MS Guidelines clearly state that .Dispose()  methods should not throw so even though it is "odd" that the object is disposed multiple times, it shouldn't  happen.

As a workaround you could debug/check where these multiple disposal calls are coming from and if you can influence that try to reduce them to one.

**Comment by jbattermann** [comment]
Fix has been merged, new version should appear shortly on nuget.
