### ISSUE TITLE
This Package vs Microsoft.ApplicationInsights.AspNetCore

### ISSUE THREAD

**Issue by RehanSaeed** [serilog/serilog-sinks-applicationinsights#48]
What is the difference between this package and using `Microsoft.ApplicationInsights.AspNetCore`? Is there anything that is logged differently? I suppose this package will not handle any client side logging that the application insights package handles.

Also as an aside, if I'm already using `Log.CloseAndFlush()`, do I really need to also call `telemetryClient.Flush()` or use persisted channels? Is there an opportunity to simplify here?

**Comment by nblumhardt** [comment]
Hi @RehanSaeed - do you mean: _in the case that one is using Microsoft.Extensions.Logging for all logging, and not Serilog.AspNetCore_?

If you use the most recent Serilog integration for ASP.NET Core, this package is the Serilog replacement for the default MEL AI provider. You get all the goodness of the Serilog pipeline:

 * Enrichment in all its glorious forms
 * Filtering including filter expressions
 * The million-and-one other awesome Serilog sinks
 * A great ecosystem of Serilog community packages like _Serilog.Exceptions_ :-)

:-) might need more context to provide a better answer here - @jbattermann generally knows the ins-and-outs of the AI telemetry client and this sink, so might have more to add.

Cheers!
Nick

**Comment by RehanSaeed** [comment]
Hi @nblumhardt I suppose what I'm asking is:

1. How is client side JavaScript logging handled. `Microsoft.ApplicationInsights.AspNetCore` injects a script tag for that.
2. What do I see in the Azure AI Portal that is different when I use this package?

**Comment by jenyayel** [comment]
IMHO those are just different products. You get much more with AI besides application logging and you get much more with Serilog for application logging. I have projects where we use both together. 

AI is about metrics, profiling, logs and not just backend application logs, but also infrastructure and front end.  Besides, it is also you can view those data points in different parts of Visual Studio and in Azure portal. 

Serilog is about taking care of formatting and shipping logs. And it does it very very well. We have products where we'll ship to AI, ELK and console in one environment and in another environment we'll ship to totally different places, while having different formats for each of those sinks.

**Comment by RehanSaeed** [comment]
@jenyayel Using both is an interesting idea. I'm still interested in # 2 I raised above (I suppose I can bite the bullet and try it out). I've raised https://github.com/serilog/serilog-sinks-applicationinsights/issues/48 for # 3.

**Comment by jenyayel** [comment]
Regarding second bullet, from what I know is that when you use this package you'll be able to see **only** your application logs - either under events or traces.

**Comment by philmarland** [comment]
Regarding using both, I'm also interested since the instructions on the Serilog.AspNetCore package (https://github.com/serilog/serilog-aspnetcore/blob/dev/README.md) say the following:

- Remove UseApplicationInsights() (this can be replaced with the Serilog AI sink, if required)

To my mind, this suggests that the combination of Serilog.AspNetCore and Serilog.Sinks.ApplicationInsights would cover everything that UseApplicationInsights() entails, but this doesn't seem to be the case.

I'm trying to get my head around what the ideal setup is for an ASP.Net Core project making the fullest possible use of Application Insights.

**Comment by nblumhardt** [comment]
@philmarland definitely need more exploration in that area - it'd be interesting to hear what you find if you are able to try enabling both. Could be a good discussion for the https://github.com/serilog/serilog-aspnetcore repo rather than here, since the sink is general across app models.

**Comment by seniorquico** [comment]
In case anyone is still interesting in this issue... I've setup a project with both the `Microsoft.ApplicationInsights.AspNetCore` and `Serilog.Sinks.ApplicationInsights` packages. I have some notes and example configurations in the following thread.

https://github.com/serilog/serilog-aspnetcore/issues/52

I've been running with the configuration for a few days, and it appears to be working well.

**Comment by aloneguid** [comment]
closing as the question is answered - Serilog.AspNetCore is the way to go
