### ISSUE TITLE
Metric-friendly types should populate AI .Metrics by default

### ISSUE THREAD

**Issue by brettveenstra** [serilog/serilog-sinks-applicationinsights#49]
New to AI here but wondering why mappings (e.g. https://github.com/serilog/serilog-sinks-applicationinsights/blob/master/src/Serilog.Sinks.ApplicationInsights/Sinks/ApplicationInsights/ApplicationInsightsPropertyFormatter.cs#L18) are not going to the `.Metrics` instead of `.Properties`?

Booleans, Numerics, Temporals and Guids (as defined https://github.com/serilog/serilog/wiki/Structured-Data) make sense as default behavior with possibility to opt-out during `.WriteTo` configuration.

**Comment by aloneguid** [comment]
You can always override the standard behavior. Trace telemetry doesn't have metrics, and we keep it really generic.
