### ISSUE TITLE
System.MissingMethodException after nuget upgrade

### ISSUE THREAD

**Issue by eaidland** [serilog/serilog-sinks-applicationinsights#51]
Hi!
I'm getting errors while running my function after upgrading package to latest version from Nuget. Not sure which methods missing, but it's running ok if I remove the  .WriteTo.ApplicationInsightsEvents("XXXXXXXXXX");

**Update:**
I've rolled back to Microsoft.ApplicationInsights v2.4.0 from v2.5.1 and now it's working

Serilog v2.6.0
Serilog.Sinks.ApplicationInsights v2.5.1

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Serilog.LoggerConfiguration Serilog.LoggerConfigurationApplicationInsightsExtensions.ApplicationInsightsEvents(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.IFormatProvider, System.Func`3<Serilog.Events.LogEvent,System.IFormatProvider,Microsoft.ApplicationInsights.Channel.ITelemetry>)'.

`ILogger logger = UseSerilogLogger().CreateLogger();`
   ```
public static LoggerConfiguration UseSerilogLogger()
        {
            return new LoggerConfiguration()
                   .MinimumLevel.Debug()
                   .Enrich.FromLogContext()
                   .WriteTo.ApplicationInsightsEvents("XXXXXXXXXX");
        }
```

**Comment by aloneguid** [comment]
We can update references in this lib to the latest AI, would it help? I can't think of any potential dangers so far.

**Comment by aloneguid** [comment]
upgraded to latest AI
