### ISSUE TITLE
Log.CloseAndFlush Should Call TelemetryClient.Flush

### ISSUE THREAD

**Issue by RehanSaeed** [serilog/serilog-sinks-applicationinsights#53]
If I'm already using `Log.CloseAndFlush()`, I really shouldn't need to also call `telemetryClient.Flush()` or use persisted channels? Is there an opportunity to simplify here? Perhaps Serilog core should provide a hook, so that sinks can cleanup any resources they are using.

**Comment by nblumhardt** [comment]
I'm not familiar enough with AI's client API to help here, but if the sink implements `IDisposable` that would be the proper place to call `telemetryClient.Flush()`, at least in Serilog terms (`Log.CloseAndFlush()` will dispose any attached sinks.)

**Comment by jbattermann** [comment]
It is and it already does: https://github.com/serilog/serilog-sinks-applicationinsights/blob/master/src/Serilog.Sinks.ApplicationInsights/Sinks/ApplicationInsights/ApplicationInsightsSinkBase.cs .. see .Dispose(...) method.

Ai sends the data in the background and does not block afaik & if your process shuts down ‚quickly‘ after it disposes the sink there‘s nothing we/the sink can do.

On 13. Mar 2018, at 01:02, Nicholas Blumhardt <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not familiar enough with AI's client API to help here, but if the sink implements IDisposable that would be the proper place to call telemetryClient.Flush(), at least in Serilog terms (Log.CloseAndFlush() will dispose any attached sinks.)

**Comment by RehanSaeed** [comment]
In that case it might be worth updating the [documentation](https://github.com/serilog/serilog-sinks-applicationinsights#how-when-and-why-to-flush-messages-manually) which suggests that you need to call `Flush` yourself when all you really need to do is call `await Task.Delay(1000)`.

I've suggested that AI add a `FlushAsync` method that can be awaited [here](https://github.com/Microsoft/ApplicationInsights-aspnetcore/issues/304).

**Comment by jbattermann** [comment]
That's exactly what's already outlined here: https://github.com/serilog/serilog-sinks-applicationinsights#using-ai-persistent-channels

.. which already states (and also also links to the lengthy discussion): "[...]By default the Application Insights client and therefore also this Sink use an in-memory buffer of messages which are sent out periodically whenever the AI client deems necessary. This may lead to unexpected behaviour upon process termination, particularly not all of your logged messages may have been sent and therefore be lost.[...]"


If you want a better explanation / separate area added explaining it, you're welcome to submit a PR for the Readme.md.
<https://github.com/serilog/serilog-sinks-applicationinsights#using-ai-persistent-channels>

________________________________

**Comment by aloneguid** [comment]
closing as readme already contains this clause
