### ISSUE TITLE
How to pass cloud roleName as part of Logger Initialization

### ISSUE THREAD

**Issue by wahabakhtar** [serilog/serilog-sinks-applicationinsights#54]
We are using different cloud roleNames to identify different components of the application. Is there a way to set some defaults in telemetry context as part of Logger Initialization? 

I can do that when using telemetry client directly:
https://github.com/Azure-Samples/application-insights-dotnet-data-reduction/blob/master/ApplicationInsightsDataROI/DefaultTelemetryInitializer.cs

**Comment by jbattermann** [comment]
See the example in the https://github.com/serilog/serilog-sinks-applicationinsights/blob/master/README.md .. the one with 

```
    // then go ahead and post-process the telemetry's context to contain the user id as desired
    if (logEvent.Properties.ContainsKey("UserId"))
    {
        telemetry.Context.User.Id = logEvent.Properties["UserId"].ToString();
    }
```
.. in it (4th 'colored' box) and there you can access the .Context.* sub properties obviously, including the ones in your sample code.

**Comment by stuarthallows** [comment]
```cs
telemetry.Context.Cloud.RoleName = _roleName;
telemetry.Context.Cloud.RoleInstance = _roleInstance;
```
