### ISSUE TITLE
Add LogContext Properties to request object custom dimensons.

### ISSUE THREAD

**Issue by zippy1981** [serilog/serilog-sinks-applicationinsights#58]
I was trying to figure out how to do this myself in an Initializer or Middleware. 

When you use this Sink, you get Requests logged "for free" as a matter of course of it initializing the Application Insights ASP.NET Core library. If you want to inject

        public static IApplicationBuilder AddSerilogContextToRequestTelemetry(this IApplicationBuilder builder)
        {
            return builder.Use(async (context, next) =>
            {
                var requestTelemetry = context.Features.Get<RequestTelemetry>();
               requestTelemetry.Context.Properties['Key"] = "Value";
                await next.Invoke();
            });
        }

I'm not sure where all the variables pushed into `LogContext` are publically exposed, but once you have the RequestTelemetry object in a place where you can iterate over the scope its easy to get them.

The real issue is where and how to configure this, if this should be default (I don't see an issue because worse case its just extra data if someone upgrades serilog).

However, I think it really makes sense for the log context data to show up in the request object.

**Comment by aloneguid** [comment]
it's not an issue of this sink as it picks up log context by default, but in order for Serilog to push down log context you need to call `.Enrich.FromLogContext()` in logger initialisation.
