### ISSUE TITLE
Passing IServiceProvider to extension methods.

### ISSUE THREAD

**Issue by zippy1981** [serilog/serilog-sinks-applicationinsights#62]
In Asp.NET core it seems that its not recommended to use `TelemetryConfiguration.Active`  Its much preferable to use `IServiceProvider.GetRequiredService<TelemetryConfiguration>()` or `IServiceProvider.GetRequiredService<TelemetryClient>()`. 

So, doing this is easy, but it requires adding Microsoft.Extensions.DependencyInjection. Is that ok with you?

**Comment by aloneguid** [comment]
I think introducing a dependency on specific DI framework is against good design practices. If someone is not using this DI it will be still downloaded into an app. You can always get the TelemetryConfiguration instance from DI and pass to this sink?
