### ISSUE TITLE
Provide support for operation_Id

### ISSUE THREAD

**Issue by tomkerkhove** [serilog/serilog-sinks-applicationinsights#64]
Are there plans to provide support for operation_Id so that telemetry is correlated out-of-the-box in Application Insights?

**Comment by aloneguid** [comment]
Good question, it depends.

AI does not set `operation_Id` automatically, so the question is what exactly should we consider "out of the box".

For instance, in asp.net core a custom middleware from Microsoft generates `operation_Id` on incoming request, either by injecting a new one, or based on incoming request headers if they are present. I assume you mean taking this `operation_Id` and pushing to Serilog's log context, in which case it will be responsibility of asp.net core middleware?

**Comment by tomkerkhove** [comment]
It should be provided indeed outside of Serilog, but if it is there we should assign it to [OperationContext.Id](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.extensibility.implementation.operationcontext.id?view=azure-dotnet#Microsoft_ApplicationInsights_Extensibility_Implementation_OperationContext_Id).

But to be fair, I don't have experience with Serilog so I'm not sure if and how we can pass the operationId.

**Comment by aloneguid** [comment]
We could check if custom property `operation_Id` exists in current log context, and push it over to operation context, if it's not set. This will only affect default behavior, as you can always set operation id right now via custom conversion method.

**Comment by aloneguid** [comment]
added in 3.0.2, if `operationId` is in logEvent properties it will be picked up ;)

**Comment by jchannon** [comment]
Is there an example of how to set this property or is there something in Serilog.AspNetCore package that might set this to the request id?

**Comment by jchannon** [comment]
For others, (thanks to @nblumhardt) you'll need the below class and extra config

`.Enrich.With(new OperationIdEnricher())`

```
public class OperationIdEnricher : ILogEventEnricher
    {
        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
        {
            if (logEvent.Properties.TryGetValue("RequestId", out var requestId))
            {
                logEvent.AddPropertyIfAbsent(new LogEventProperty("operationId", requestId));
            }
        }
    }
```

**Comment by tomkerkhove** [comment]
Thanks for the sample @jchannon 	!

**Comment by dominiclapointe** [comment]
Is there the same for UserId and AuthenticatedUserId?
