### ISSUE TITLE
Reference to RequestTelemetryEnricherOptions?

### ISSUE THREAD

**Issue by jsancho** [serilog/serilog-sinks-applicationinsights#67]
The README file recommends the following as a way to configure ApplicationInsights for ASP .NET Core

```
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<RequestTelemetryEnricherOptions>(Configuration);
    services.AddApplicationInsightsTelemetry();
    ...
}
```
However, when I try to use that code I cannot resolve the reference to `RequestTelemetryEnricherOptions`.
I've not been able to find that enricher in this package or googling away.

Is there something obvious that I'm missing?

thanks,

Jaume

**Comment by RinNguyenKms** [comment]
Same issue for me

**Comment by thj-dk** [comment]
Same issue here.

**Comment by shobman** [comment]
Me too

**Comment by DinoSourcesRex** [comment]
@jsancho Did you ever resolve this?

**Comment by jessebarocio** [comment]
I wasn't able to find the referenced class anywhere but the package seems to work fine without that line. It's probably just outdated documentation.

**Comment by aloneguid** [comment]
Seems like documentation is up to date now. Closing this issue.
