### ISSUE TITLE
Dependency issue when installing Serilog.Sinks.ApplicationInsights 2.6.0 : "Microsoft.ApplicationInsights.DependencyCollector 2.4.1 requires Microsoft.ApplicationInsights (= 2.4.0) "

### ISSUE THREAD

**Issue by lioobayoyo** [serilog/serilog-sinks-applicationinsights#68]
When installing Serilog.Sinks.ApplicationInsights 2.6.0, I have the following warning : 

Warning	NU1608 Detected package version outside of dependency constraint: Microsoft.ApplicationInsights.DependencyCollector 2.4.1 requires Microsoft.ApplicationInsights (= 2.4.0) but version Microsoft.ApplicationInsights 2.5.1 was resolved.

if I roll back to Serilog.Sinks.ApplicationInsights 2.5.2, no problem.

Not sure if it's a bug in Microsoft.ApplicationInsights.DependencyCollector 2.4.1 or in Serilog.Sinks.ApplicationInsights 2.6.0 .

Please don't hesitate to ask if more info is needed.

**Comment by skotl** [comment]
I confirm that downgrading from Serilog.Sinks.ApplicationInsights 2.6.0 to 2.5.2 removes the dependency warning.

**Comment by davidp1978** [comment]
Explicitly installing NuGet packages for Microsoft.ApplicationInsights and Microsoft.ApplicationInsights.DependencyCollector seems to work. I have these installed:
- Serilog.Sinks.ApplicationInsights 2.6.0
- Microsoft.ApplicationInsights 2.8.1
- Microsoft.ApplicationInsights.DependencyCollector 2.8.1

**Comment by aloneguid** [comment]
Should we upgrade AI dependency in this library and up the minor version? It seems quite old to me.

**Comment by aloneguid** [comment]
upgraded to latest AI
