### ISSUE TITLE
Why are messages logged as events?

### ISSUE THREAD

**Issue by tyjen** [serilog/serilog-sinks-applicationinsights#7]
I'm curious as to why log messages are sent to AppInsights as custom events. This really clutters up my own custom events and instead should go to the "Traces" section of the AppInsights Analytics tool by using the TelemetryClient.TrackTrace function instead of TrackEvent.

**Comment by jbattermann** [comment]
Whether the messages are events or traces could be debated but probably every user might have a different opinion about that. Sending them as events was chosen early on and I wouldn't change that default behaviour now.

However, I certainly do think that you have a point here and I'll go ahead and make that option available so users can choose to send them as traces rather than events.

**Comment by jbattermann** [comment]
Quick update: with the latest commit / build you can now choose whether to send the Serilog LogEvents as Events or Traces, see the [Readme](https://github.com/serilog/serilog-sinks-applicationinsights/blob/master/README.md) how to do that.

Cheers,
-J

**Comment by tyjen** [comment]
Excellent, thanks for the quick action!

**Comment by tyjen** [comment]
Just tried updating to v2.0.32 but I'm running into dependency issues. The version of AppInsights the sink requires is >= 2.0.1, but the various other AppInsights packages require AppInsights v2.0.0 strict, therefore I cannot update to the latest sink package. Is it possible to make the sink dependent on AppInsights 2.0.0 so it will work with all the other packages?

Here's the full details of the issue:

> Attempting to resolve dependencies for package 'Microsoft.ApplicationInsights.2.0.1' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'Microsoft.ApplicationInsights 2.0.1' is not compatible with 'Microsoft.ApplicationInsights.DependencyCollector 2.0.0 constraint: Microsoft.ApplicationInsights (= 2.0.0)', 'Microsoft.ApplicationInsights.PerfCounterCollector 2.0.0 constraint: Microsoft.ApplicationInsights (= 2.0.0)', 'Microsoft.ApplicationInsights.Web 2.0.0 constraint: Microsoft.ApplicationInsights (= 2.0.0)', 'Microsoft.ApplicationInsights.WindowsServer 2.0.0 constraint: Microsoft.ApplicationInsights (= 2.0.0)', 'Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel 2.0.0 constraint: Microsoft.ApplicationInsights (= 2.0.0)', 'Serilog.Sinks.ApplicationInsights 2.0.32 constraint: Microsoft.ApplicationInsights (>= 2.0.1)'.

**Comment by jbattermann** [comment]
Oh my.. yeah - that strict '2.0.0' dependency for these other AI packages is a bit odd but I see no reason why the Sink here could not use that (min) version as well.

I am currently at a client's site and cannot fix it right away, but will submit the fix as soon as I get back in my office.

If you need it fixed urgently, you can also fork & perform the fix yourself and send over the PR.. that I could merge in from here, too.

**Comment by jbattermann** [comment]
Alright - switched the Sink's dependency to 2.0.0.. hope that works / helps!

**Comment by tyjen** [comment]
Confirmed the packaging is working nicely now, and I was able to use the new config api. Thank you!

**Comment by grik001** [comment]
Quick Question, how can this be achieved using appsettings?

![image](https://user-images.githubusercontent.com/27157850/36671607-882fd10c-1afc-11e8-9091-54a495410cbd.png)
