### ISSUE TITLE
Strategy to avoid duplicated exceptions

### ISSUE THREAD

**Issue by joaopgrassi** [serilog/serilog-sinks-applicationinsights#71]
Hi,

I'm trying to integrate this sink within my application. I managed to add everything and all works fine. But, I'm a bit lost trying to get rid of duplicate exceptions on AI.  I configured the sink with all the defaults: `ApplicationInsightsTraces`, just providing the key. 

When looking at AI, I always see this:
![Exception Duplication](https://i.imgur.com/tt3QNdO.png)

AI logs the request and the exception automatically. I then, in my global error logger (WebAPI, IExceptionlogger) do `_logger.Error(...)` and it gets sent as Trace. 

So, how can I avoid duplicate errors, while logging myself the exception? I read in the docs, where there's the customization method (ConvertLogEventsToCustomTraceTelemetry).. where it's mentioned to return `null` from the converter method in case you want to ignore the event. Should I be doing that to solve this?

Would appreciate some guidance. Cheers!

**Comment by aloneguid** [comment]
Yes you can return `null` from customisation logic if you want to ignore it. As you are already logging the error from your custom middleware.
