### ISSUE TITLE
Sending RequestData to ApplicationInsights

### ISSUE THREAD

**Issue by DinoSourcesRex** [serilog/serilog-sinks-applicationinsights#74]
What is the proper configuration to get this sink to send my request data to application insights?

I've done a very basic configuration so far via `appsettings.json` however the base type is never set to `RequestData`, as it would be if I was using `.UseApplicationInsights`.

Any ideas?

`appsettings.json`
```
"Serilog": {
    "Using": [ "Serilog.Sinks.ApplicationInsights" ],
    "MinimumLevel": {
      "Default": "Debug",
      "Override": {
        "Microsoft": "Warning",
        "System": "Warning"
      }
    },
    "WriteTo": [
      {
        "Name": "ApplicationInsightsEvents",
        "Args": {
          "restrictedToMinimumLevel": "Information",
          "instrumentationKey": ""
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithExceptionDetails" ],
    "Properties": {
      "Application": "Name"
    }
  }
```

**Comment by aloneguid** [comment]
I guess it's related to ASP.NET? In that case you should use asp.net sink for serilog, it enables standard web telemetry, including request data.

**Comment by DinoSourcesRex** [comment]
@aloneguid I've already got `Serilog.AspNetCore` included. It's not being sent.

**Comment by tomkerkhove** [comment]
@DinoSourcesRex 	You should be able to do this now with 3.0.0 - https://github.com/serilog/serilog-aspnetcore#request-logging-300-
