### ISSUE TITLE
How to set tags

### ISSUE THREAD

**Issue by DinoSourcesRex** [serilog/serilog-sinks-applicationinsights#75]
I am interested in being able to set my own custom tags / overwrite default tags.

An example json sent to application insights from this sink is;

```
{
    "name": "",
    "time": "",
    "iKey": "",
    "tags": {
        "ai.application.ver": "",
        "ai.user.id": "",
    },
    "data": {
        "baseType": "RequestData",
        "baseData": {
            }
        }
    }
}
```

How do I go about editting the values of ai.user.id? Or ai.application.ver?

**Comment by aloneguid** [comment]
Tags are included in `telemetry.Context` but called slightly different, for instance `ai.application.ver` is `telemetry.Context.User.Id` etc.
