### ISSUE TITLE
Question: TelematryClient disable sampling

### ISSUE THREAD

**Issue by stridsbr** [serilog/serilog-sinks-applicationinsights#78]
I use application insights for my tracelogging in .net framework. But the logs are sampled.
This is how I create the client:
```csharp
var client = new TelemetryClient()
            {
                InstrumentationKey = _instrumentationKey
            };
var log = new LoggerConfiguration()
        .WriteTo
        .ApplicationInsights(client , ConvertLogEventsToCustomTraceTelemetry)
        .CreateLogger();
```
How can I modify this code so it dont get sampled?
Or that Trace and exception logs won't get sampled?

**Comment by aloneguid** [comment]
@stridsbr sampling should be off by default, that's what I see when creating TelemetryClient manually like you do. You've mentioned that it's used in Azure Functions runtime. Are you sure the sampled telemetry is actually coming from your ILogger and not from some built-in AppInsights integration in azure functions? Have you tried inspecting `TelemetryConfiguration.Active` instead and check that it doesn't have sampling pre-configured by functions runtime?

**Comment by stridsbr** [comment]
I had an issue in the the function runtime repo and the responsen was that the logconfiguration don't change the logging config of manually created telemetryclients.

I have refactored the code and I think the issue was that I created a new telemetryclient in edge cases.
