### ISSUE TITLE
The document needs to be updated in the scope of ServerTelemetryChannel

### ISSUE THREAD

**Issue by Arash-Sabet** [serilog/serilog-sinks-applicationinsights#81]
The last section of document i.e. "Using AI Persistent Channels" needs to be updated. In step 1 it suggests that ```Microsoft.ApplicationInsights.PersistenceChannel``` nuget package needs to be added to the project. That package causes inconsistency and warnings when restoring nuget packages. Having said that, the most up-to-date package to add as a reference is ```Microsoft.ApplicationInsights.AspNetCore```.

**Comment by jbattermann** [comment]
Hmmm.. according to https://github.com/Microsoft/ApplicationInsights-Home/issues/30#issuecomment-418826972 persistence channels is no longer available.. at all.. for >= 2.0.0 - so the Microsoft.ApplicationInsights.AspNetCore package won't help here either.

The only 'similar' / maintained successor package is the [Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel](https://www.nuget.org/packages/Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel/) one.. but geared towards a different scenario (server use) than the old one was (desktop use).

So it might make more sense removing that paragraph entirely..

**Comment by Arash-Sabet** [comment]
@jbattermann So I will create another pull request by removing that paragraph. Would you please reject the older one? Thanks.

**Comment by aloneguid** [comment]
Would it be better to find a way to use persistent channels in AI rather that delete it? Maybe worth raising an new issue?

**Comment by aloneguid** [comment]
closing this as readme is updated now, the issue with persistence channels is tracked in #19
