### ISSUE TITLE
Update AppInsights SDK from 2.5.1 to 2.9.1

### ISSUE THREAD

**Issue by abergs** [serilog/serilog-sinks-applicationinsights#94]
Latest is 2.9.1
https://www.nuget.org/packages/Microsoft.ApplicationInsights
Install-Package Microsoft.ApplicationInsights -Version 2.9.1

**Comment by aloneguid** [comment]
If other people have no issues with this i'm happy to update.

**Comment by aloneguid** [comment]
updated

**Comment by schappa** [comment]
I think there is a problem with doing this upgrade.  AI is reporting the below error when using Serilog.ApplicationInsights 3.0.2:

AI (Internal): ERROR: Exception in Command Processing for EventSource Microsoft-ApplicationInsights-Data: An instance of EventSource with Guid a62adddb-6b4b-519d-7ba1-f983d81623e0 already exists.

I think this has something to do with it:
https://github.com/Microsoft/ApplicationInsights-dotnet-logging/issues/237
